version: '2.2'
services:

  fake-percolator:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.bench
    command: ["clojure", "-m", "bench.server"]

  bench:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.bench
    volumes:
      - ../vals/:/usr/src/app/vals/
    command: ["clojure",
              "-m", "bench.phrases",
              "-t", "resources/b.csv",
              "-k", "content",
              "--implementation", "fake-percolator",
              "--es-host", "http://fake-percolator:9200",
              "-o", "/usr/src/app/vals/vals.json"]
