version: '2.2'
services:

  face-percolator:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.bench
    command: ["clojure", "-m", "bench.server"]

  bench:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.bench
    volumes:
      - ../vals/:/usr/src/app/vals/
    command: ["clojure",
              "-m", "bench.phrases",
              "-t", "resources/top-1000.csv",
              "-k", "text",
              "-implementation", "fake-percolator",
              "--es-host", "http://face-percolator:9200",
              "-o", "/usr/src/app/vals/vals.json"]
